// Extract the step-by-step trace the loop visualisation draws, from two real
// cascade receipts covering the SAME case. The pairing is the whole point: the
// loop and the gate are identical in both, so the only thing that differs is
// whether the judge's confidence clears the bar.
//
// Receipts live under .scratch, which is not committed, so the extracted trace
// is written to site/loop-data.js and committed alongside the page that draws
// it. Re-run this whenever the receipts are regenerated.
import { readFile, writeFile } from "node:fs/promises";
import { parseArgs } from "node:util";

const { values } = parseArgs({
  options: {
    typesafe: { type: "string", default: ".scratch/cascades/1b5c882e-1bd3-4b40-9820-e37e38ea04c0/cascade.json" },
    cascade: { type: "string", default: ".scratch/cascades/33111c36-0616-434e-ad10-0bba0d70a2c6/cascade.json" },
    case: { type: "string", default: "archive_toggles_unread" },
    out: { type: "string", default: "site/loop-data.js" },
  },
});

type Answer = { choice: string; confidence: number; probabilities: Record<string, number> };
type Step = {
  role: string;
  questions: Record<string, { criteria: Record<string, string> }>;
  judgment: { model: string; answers: Record<string, Answer>; usage: Usage; latencyMs: number };
};
type Usage = { inputTokens: number; outputTokens: number };
type Attempt = { tier: string; verdict: string; reason: string; latencyMs: number; usage: Usage };
type Row = {
  caseId: string;
  expected: string;
  verdict: string;
  escalations: number;
  totalLatencyMs: number;
  totalUsage: Usage;
  attempts: Attempt[];
  final: { verdict: string; reason: string; minConfidence: number; evidenceIds: string[]; steps: Step[] };
};

async function row(path: string, caseId: string): Promise<{ policy: string; row: Row }> {
  const report = JSON.parse(await readFile(path, "utf8")) as { policy: string; rows: Row[] };
  const found = report.rows.find((r) => r.caseId === caseId);
  if (!found) throw new Error(`${path} has no case ${caseId}`);
  return { policy: report.policy, row: found };
}

// One step, flattened to what the visualisation needs: who spoke, what they
// chose, how sure they were, and the full distribution behind that choice.
function steps(list: Step[]) {
  return list.map((step, index) => ({
    i: index + 1,
    role: step.role,
    model: step.judgment.model,
    latencyMs: Math.round(step.judgment.latencyMs),
    usage: step.judgment.usage,
    answers: Object.entries(step.judgment.answers).map(([question, answer]) => ({
      q: question,
      choice: answer.choice,
      confidence: answer.confidence,
      probs: answer.probabilities,
      criteria: step.questions[question]?.criteria ?? {},
    })),
  }));
}

const typesafe = await row(values.typesafe!, values.case!);
const cascade = await row(values.cascade!, values.case!);
if (typesafe.policy !== "typesafe") throw new Error(`${values.typesafe} is not a typesafe-policy run`);
if (cascade.policy !== "cascade") throw new Error(`${values.cascade} is not a cascade-policy run`);

const data = {
  case: values.case,
  expected: typesafe.row.expected,
  // Both receipts ran the same gate. If that ever stops being true the pairing
  // is no longer a like-for-like comparison, so refuse rather than mislead.
  minConfidence: typesafe.row.final.minConfidence,
  evidence: typesafe.row.final.evidenceIds,
  runs: [
    {
      id: "typesafe",
      label: "TypeSafe alone",
      verdict: typesafe.row.verdict,
      reason: typesafe.row.final.reason,
      correct: typesafe.row.verdict === typesafe.row.expected,
      latencyMs: Math.round(typesafe.row.totalLatencyMs),
      usage: typesafe.row.totalUsage,
      escalations: typesafe.row.escalations,
      attempts: typesafe.row.attempts.map((a) => ({ ...a, latencyMs: Math.round(a.latencyMs) })),
      steps: steps(typesafe.row.final.steps),
    },
    {
      id: "cascade",
      label: "Cascade",
      verdict: cascade.row.verdict,
      reason: cascade.row.final.reason,
      correct: cascade.row.verdict === cascade.row.expected,
      latencyMs: Math.round(cascade.row.totalLatencyMs),
      usage: cascade.row.totalUsage,
      escalations: cascade.row.escalations,
      // The cascade's first tier abstained and was discarded, so its steps are
      // not in this receipt. Carry the tier summary the receipt does hold,
      // rather than borrowing the other run's steps and implying they are the
      // same execution.
      attempts: cascade.row.attempts.map((a) => ({ ...a, latencyMs: Math.round(a.latencyMs) })),
      steps: steps(cascade.row.final.steps),
    },
  ],
};

if (cascade.row.final.minConfidence !== data.minConfidence) {
  throw new Error("The two runs used different gates; they are not comparable");
}

await writeFile(values.out!, `// Generated by scripts/loop-data.ts. Do not edit by hand.\nwindow.LOOP_DATA = ${JSON.stringify(data, null, 1)};\n`);
console.log(`Wrote ${values.out} — ${data.runs.map((r) => `${r.id}: ${r.steps.length} steps, ${r.verdict}`).join("; ")}`);
